@startuml Minimal Fisher State Diagram
title Діаграма станів: Рибалка

[*] -> Неактивний : конструктор
Неактивний -> Планування : планувати()
Планування -> Активний : розпочати()
Активний -> Завершення : завершити()
Завершення -> Неактивний : {final} звіт()

state Активний {
  [*] -> Переміщення
  Переміщення -> Ловля : прибути()
  Ловля -> Реєстрація : виловити()
  Реєстрація -> Ловля : продовжити()
  Ловля -> [*] : завершити()
}

@enduml